### ISSUE TITLE
URGENT: capability to change how many tops/sends are included in the score

### ISSUE THREAD

**Issue by badpens** [jsnyders/ClimbingComp#13]
we might need to change from "top 5" to "top 4" or "top 3" sends to create the score.

**** this might apply to tomorrow's BRG comp. ****

**Comment by badpens** [comment]
score is top N scores, where N is configurable.

However, for BRG comp tomorrow, N will be 3, 4, or 5.

**Comment by badpens** [comment]
95% sure BRG comp will use top 3 sends.

**Comment by jsnyders** [comment]
Interstingly I was reviewing the USA climbing rules last night and noticed that the official top number of climbs is 3 for SCS and 5 for ABS. So yes it should be configurable. I have made the change so that it is set to 3 for tomorrow but it is not yet configurable. 
Leaving enhancement open until it is configurable.

**Comment by jsnyders** [comment]
Number of top routes to include in total score for red point format comp is now implemented. You select the number of tops when you create the event. Values are 1 to 6.
